# This file was generated by GoReleaser. DO NOT EDIT.
cask "kb" do
  version "0.0.4"

  on_macos do
    on_intel do
      url "https://github.com/compozy/kb/releases/download/v#{version}/kb_#{version}_darwin_x86_64.tar.gz"
      sha256 "463e4a9d6450c2b103042f5b7624145a2da2d638b4b89456ac672c6abac42d19"
      rename "kb_0.0.4_darwin_x86_64/kb", "kb"
    end
    on_arm do
      url "https://github.com/compozy/kb/releases/download/v#{version}/kb_#{version}_darwin_arm64.tar.gz"
      sha256 "9689494f70d4d58876dd6904a672bbc9ec93c9c32410d1db9cb8bd41e7e53eb8"
      rename "kb_0.0.4_darwin_arm64/kb", "kb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/compozy/kb/releases/download/v#{version}/kb_#{version}_linux_x86_64.tar.gz"
      sha256 "a7caa0f5dc7b522c9f2a6b02c71886de9a22ae0ddd34ccc21ff7afcfb35bfc0e"
      rename "kb_0.0.4_linux_x86_64/kb", "kb"
    end
    on_arm do
      url "https://github.com/compozy/kb/releases/download/v#{version}/kb_#{version}_linux_arm64.tar.gz"
      sha256 "065459d15bed77f3f2add04df5aeabd1a905dd7591628af28a68f55fe50947bc"
      rename "kb_0.0.4_linux_arm64/kb", "kb"
    end
  end

  name "kb"
  desc "CLI for building topic-based knowledge bases in the Karpathy KB pattern"
  homepage "https://github.com/compozy/kb"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kb"

  # No zap stanza required

  caveats <<~EOS
    To get started with kb:
      kb topic new my-topic
    See https://github.com/compozy/kb for more information.
  EOS
end
