# This file was generated by GoReleaser. DO NOT EDIT.
cask "kb" do
  version "0.0.5"

  on_macos do
    on_intel do
      url "https://github.com/compozy/kb/releases/download/v#{version}/kb_#{version}_darwin_x86_64.tar.gz"
      sha256 "d7098ee203c3790e7d4f16c0a4becbfc80559000dadf641d40c7078f04e3600b"
      rename "kb_0.0.5_darwin_x86_64/kb", "kb"
    end
    on_arm do
      url "https://github.com/compozy/kb/releases/download/v#{version}/kb_#{version}_darwin_arm64.tar.gz"
      sha256 "8877d88dd8a0b8890509bfe64d70046ba266615790473069d721e41ae1535773"
      rename "kb_0.0.5_darwin_arm64/kb", "kb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/compozy/kb/releases/download/v#{version}/kb_#{version}_linux_x86_64.tar.gz"
      sha256 "d4032d6a7dc62f07e8b2abb602d6ec0a44f2f78b9f716ee17781c860a236f6a9"
      rename "kb_0.0.5_linux_x86_64/kb", "kb"
    end
    on_arm do
      url "https://github.com/compozy/kb/releases/download/v#{version}/kb_#{version}_linux_arm64.tar.gz"
      sha256 "ddcbb6b4040ca04cfb0d45219eaba1ae61d0522a046b7157238bda73fdc36e96"
      rename "kb_0.0.5_linux_arm64/kb", "kb"
    end
  end

  name "kb"
  desc "CLI for building topic-based knowledge bases in the Karpathy KB pattern"
  homepage "https://github.com/compozy/kb"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kb"

  # No zap stanza required

  caveats <<~EOS
    To get started with kb:
      kb topic new my-topic
    See https://github.com/compozy/kb for more information.
  EOS
end
