# This file was generated by GoReleaser. DO NOT EDIT.
cask "kb" do
  version "0.0.2"

  on_macos do
    on_intel do
      url "https://github.com/compozy/kb/releases/download/v#{version}/kb_#{version}_darwin_x86_64.tar.gz"
      sha256 "50079abf448d24dea3f2d2a813099dfcd53c2fa166f24cad58c38fc9bcbcd24f"
      rename "kb_0.0.2_darwin_x86_64/kb", "kb"
    end
    on_arm do
      url "https://github.com/compozy/kb/releases/download/v#{version}/kb_#{version}_darwin_arm64.tar.gz"
      sha256 "a6b6e7d212e0ad2da6f88d8608b57c57a9969b9287c277fd93ae23b911b1a475"
      rename "kb_0.0.2_darwin_arm64/kb", "kb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/compozy/kb/releases/download/v#{version}/kb_#{version}_linux_x86_64.tar.gz"
      sha256 "e3979c2f9972d4c06f8a9888f2b8e9b1cb24de9ba8273a1584eb9b73db0e0c00"
      rename "kb_0.0.2_linux_x86_64/kb", "kb"
    end
    on_arm do
      url "https://github.com/compozy/kb/releases/download/v#{version}/kb_#{version}_linux_arm64.tar.gz"
      sha256 "d90066efc88f999a2af5fba1de5610411398b6ca212a8f4313848701d67b6f82"
      rename "kb_0.0.2_linux_arm64/kb", "kb"
    end
  end

  name "kb"
  desc "CLI for building topic-based knowledge bases in the Karpathy KB pattern"
  homepage "https://github.com/compozy/kb"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kb"

  # No zap stanza required

  caveats <<~EOS
    To get started with kb:
      kb topic new my-topic
    See https://github.com/compozy/kb for more information.
  EOS
end
