# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kb < Formula
  desc "CLI for building topic-based knowledge bases in the Karpathy KB pattern"
  homepage "https://github.com/compozy/kb"
  version "0.0.8"
  license "BSL-1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/compozy/kb/releases/download/v0.0.8/kb_0.0.8_darwin_x86_64.tar.gz"
      sha256 "99289ce7693a1db1ecab1fabbe7b00df448ee96b53fb77768031dd1650dff4e0"

      define_method(:install) do
        bin.install "kb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/compozy/kb/releases/download/v0.0.8/kb_0.0.8_darwin_arm64.tar.gz"
      sha256 "3595419880649ab7468f133cb09f958367a7678722b1841413e392697abad27c"

      define_method(:install) do
        bin.install "kb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/compozy/kb/releases/download/v0.0.8/kb_0.0.8_linux_x86_64.tar.gz"
      sha256 "6170bd8281fd3dec5c2e4108955eb8242dd9d35c111291cfacbe1a469f89b0ad"
      define_method(:install) do
        bin.install "kb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/compozy/kb/releases/download/v0.0.8/kb_0.0.8_linux_arm64.tar.gz"
      sha256 "3bf7ff473cd11cb68b99681cc0328c57476c5cdc017eac4ffa0f383d0c0c5ac2"
      define_method(:install) do
        bin.install "kb"
      end
    end
  end

  def caveats
    <<~EOS
      To get started with kb:
        kb topic new my-topic
      See https://github.com/compozy/kb for more information.
    EOS
  end

  test do
    system "#{bin}/kb", "version"
  end
end
