# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kb < Formula
  desc "CLI for building topic-based knowledge bases in the Karpathy KB pattern"
  homepage "https://github.com/compozy/kb"
  version "0.0.9"
  license "BSL-1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/compozy/kb/releases/download/v0.0.9/kb_0.0.9_darwin_x86_64.tar.gz"
      sha256 "228ad88469181d9cff535b94c50be757cb052625a789f62351b2fae762a5c887"

      define_method(:install) do
        bin.install "kb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/compozy/kb/releases/download/v0.0.9/kb_0.0.9_darwin_arm64.tar.gz"
      sha256 "b5f802891712e19685d436c811db7a929da4fc995bc73120ddd2233b58a3dd79"

      define_method(:install) do
        bin.install "kb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/compozy/kb/releases/download/v0.0.9/kb_0.0.9_linux_x86_64.tar.gz"
      sha256 "9a87b383c8c2c286ff584c265d3229ab4696713c08cb73c7b60e02dcf54ce25e"
      define_method(:install) do
        bin.install "kb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/compozy/kb/releases/download/v0.0.9/kb_0.0.9_linux_arm64.tar.gz"
      sha256 "ffb9a2fc49da2172b95d8c4baa4edd6cdfe7d9225856cd88dd08167af2b3d9ab"
      define_method(:install) do
        bin.install "kb"
      end
    end
  end

  def caveats
    <<~EOS
      To get started with kb:
        kb topic new my-topic
      See https://github.com/compozy/kb for more information.
    EOS
  end

  test do
    system "#{bin}/kb", "version"
  end
end
