# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kb < Formula
  desc "CLI for building topic-based knowledge bases in the Karpathy KB pattern"
  homepage "https://github.com/compozy/kb"
  version "0.0.6"
  license "BSL-1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/compozy/kb/releases/download/v0.0.6/kb_0.0.6_darwin_x86_64.tar.gz"
      sha256 "3747c33620cb5a3aea88ea43f9d12a10723b6cf65c9b37de022c1c5a997b1f9b"

      define_method(:install) do
        bin.install "kb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/compozy/kb/releases/download/v0.0.6/kb_0.0.6_darwin_arm64.tar.gz"
      sha256 "b0be23ef33a5d17143179669e1a3c8934afec0016e9c9b479c549200f2cbd66c"

      define_method(:install) do
        bin.install "kb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/compozy/kb/releases/download/v0.0.6/kb_0.0.6_linux_x86_64.tar.gz"
      sha256 "89344b33269395728e6c45d1bec27271048c270c359860d68e022c3983bc9fdd"
      define_method(:install) do
        bin.install "kb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/compozy/kb/releases/download/v0.0.6/kb_0.0.6_linux_arm64.tar.gz"
      sha256 "0c11084e9760d1ce55744a4bb98d9c27530bff66f252adfc8e93bf7b80759ca5"
      define_method(:install) do
        bin.install "kb"
      end
    end
  end

  def caveats
    <<~EOS
      To get started with kb:
        kb topic new my-topic
      See https://github.com/compozy/kb for more information.
    EOS
  end

  test do
    system "#{bin}/kb", "version"
  end
end
